networks:
  front:
    driver: bridge
  messaging:
    driver: bridge
secrets:
  ADMIN_PASSWORD:
    file: ${SSL_CERTIFICATE_KEY_PASSWORD_PATH}
  USER_PASSWORD:
    file: ${SSL_CERTIFICATE_KEY_PASSWORD_PATH}
  VSI_SSL_CERTIFICATE:
    file: ${SSL_CERTIFICATE_PATH}
  VSI_SSL_CERTIFICATE_KEY:
    file: ${SSL_CERTIFICATE_KEY_PATH}
  VSI_SSL_CERTIFICATE_KEY_PASSWORD:
    file: ${SSL_CERTIFICATE_KEY_PASSWORD_PATH}
services:
  applicationcollections:
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      DB__ConnectionString: ${CONNECTION_STRING}
      DB__DbType: ${DB_TYPE}
      Hosting__VirtualDirectory: applicationCollections
      IdentityProvider__Authority: http://identityserver/identityServer
      MessageBroker__Hostname: messagebroker
      Version__Number: '0.9.34'
    image: loginvsi2/applicationcollections:0.5.0
    networks:
    - front
    - messaging
    restart: always
  applicationruns:
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      DB__ConnectionString: ${CONNECTION_STRING}
      DB__DbType: ${DB_TYPE}
      Hosting__VirtualDirectory: applicationRuns
      IdentityProvider__Authority: http://identityserver/identityServer
      MessageBroker__Hostname: messagebroker
      Version__Number: '0.9.34'
    image: loginvsi2/applicationruns:0.5.0
    networks:
    - front
    - messaging
    restart: always
  applications:
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      DB__ConnectionString: ${CONNECTION_STRING}
      DB__DbType: ${DB_TYPE}
      Hosting__VirtualDirectory: applications
      IdentityProvider__Authority: http://identityserver/identityServer
      MessageBroker__Hostname: messagebroker
      Version__Number: '0.9.34'
    image: loginvsi2/applications:0.5.0
    networks:
    - front
    - messaging
    restart: always
  comparisonengine:
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      ComparisonEngine__MatchPercentageThreshold: 95
      IdentityProvider__Authority: http://identityserver/identityServer
      MessageBroker__Hostname: messagebroker
      Services__ApplicationRunsUrl: http://applicationruns
      Services__ImageStorageUrl: http://imagestorage
    image: loginvsi2/comparisonengine:0.5.0
    networks:
    - front
    - messaging
    restart: always
  contentdelivery:
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      Hosting__HostUrls: ${ALLOWED_CLIENT_URLS}
    image: loginvsi2/contentdelivery:0.5.6
    networks:
    - front
    restart: always
  gateway:
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      START_DELAY: 10
    image: loginvsi2/gateway:0.2.4
    networks:
    - front
    - messaging
    ports:
    - ${GATEWAY_PORT}:443
    restart: always
    secrets:
    - VSI_SSL_CERTIFICATE
    - VSI_SSL_CERTIFICATE_KEY
    - VSI_SSL_CERTIFICATE_KEY_PASSWORD
  identityserver:
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      Hosting__HostUrls: ${ALLOWED_CLIENT_URLS}
      Hosting__VirtualDirectory: identityServer
      Version__Number: '0.9.34'
    image: loginvsi2/identityserver:0.1.2
    networks:
    - front
    restart: always
    secrets:
    - ADMIN_PASSWORD
    - USER_PASSWORD
  imagestorage:
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      DB__ConnectionString: ${CONNECTION_STRING}
      DB__DbType: ${DB_TYPE}
      Hosting__VirtualDirectory: imageStorage
      IdentityProvider__Authority: http://identityserver/identityServer
      Version__Number: '0.9.34'
    image: loginvsi2/imagestorage:0.2.5
    networks:
    - front
    - messaging
    restart: always
  messagebroker:
    deploy:
      restart_policy:
        condition: on-failure
    hostname: rabbitMQ-${COMPOSE_PROJECT_NAME}
    image: rabbitmq:3.7.4-management
    networks:
    - messaging
    restart: always
  notificationshub:
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      Hosting__VirtualDirectory: notificationsHub
      IdentityProvider__Authority: http://identityserver/identityServer
    image: loginvsi2/notificationshub:0.2.0
    networks:
    - front
    restart: always
  notificationsworker:
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      IdentityProvider__Authority: http://identityserver/identityServer
      MessageBroker__Hostname: messagebroker
      Services__HubUrl: ws://notificationshub/notificationsHub
    image: loginvsi2/notificationsworker:0.2.0
    networks:
    - front
    - messaging
    restart: always
  portainer:
    command: -d /data -H unix:///var/run/docker.sock --admin-password '$$2y$$05$$DTUYaqFuY0ot0BuUqKE4d.KyQmBzZiUe64rl6QLTYhS/9Nl000vK.'
    deploy:
      restart_policy:
        condition: on-failure
    image: portainer/portainer
    ports:
    - 9000:9000
    restart: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  runassignments:
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      DB__ConnectionString: ${CONNECTION_STRING}
      DB__DbType: ${DB_TYPE}
      Hosting__VirtualDirectory: runAssignments
      IdentityProvider__Authority: http://identityserver/identityServer
      MessageBroker__Hostname: messagebroker
      Version__Number: '0.9.34'
    image: loginvsi2/runassignments:0.1.3
    networks:
    - front
    - messaging
    restart: always
  runhistory:
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      DB__ConnectionString: ${CONNECTION_STRING}
      DB__DbType: ${DB_TYPE}
      Hosting__VirtualDirectory: runHistory
      IdentityProvider__Authority: http://identityserver/identityServer
      MessageBroker__Hostname: messagebroker
      Version__Number: '0.9.34'
    image: loginvsi2/runhistory:0.5.0
    networks:
    - front
    - messaging
    restart: always
  serverurls:
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      Hosting__VirtualDirectory: serverUrls
    image: loginvsi2/serverurls:0.2.3
    networks:
    - front
    restart: always
  synchronizationworker:
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      IdentityProvider__Authority: http://identityserver/identityServer
      MessageBroker__Hostname: messagebroker
      Services__ApplicationCollectionsUrl: http://applicationcollections
      Services__ApplicationRunsUrl: http://applicationruns
      Services__ApplicationsUrl: http://applications
      Services__RunAssignmentsUrl: http://runassignments
      Services__RunHistoryUrl: http://runhistory
    image: loginvsi2/synchronizationworker:0.3.0
    networks:
    - front
    - messaging
    restart: always
  ui:
    deploy:
      restart_policy:
        condition: on-failure
    image: loginvsi2/userinterface:0.5.6
    networks:
    - front
    restart: always
version: "3.1"

