networks:
  front:
    driver: overlay
  messaging:
    driver: overlay
secrets:
  ADMIN_PASSWORD:
    external: true
  ENGINE_SECRET:
    external: true
  USER_PASSWORD:
    external: true
  VSI_SSL_CERTIFICATE:
    file: ${SSL_CERTIFICATE_PATH}
  VSI_SSL_CERTIFICATE_KEY:
    file: ${SSL_CERTIFICATE_KEY_PATH}
  VSI_SSL_CERTIFICATE_KEY_PASSWORD:
    external: true
services:
  applicationcollections:
    depends_on:
    - identityserver
    - messagebroker
    deploy:
      restart_policy:
        condition: any
    environment:
      CORS__AlternativeHostUrl: https://localhost.loginvsi.com:4200
      DB__ConnectionString: ${CONNECTION_STRING};Database=ApplicationCollections;
      DB__DbType: ${DB_TYPE}
      Hosting__VirtualDirectory: applicationCollections
      IdentityProvider__Authority: http://identityserver/identityserver
      MessageBroker__Hostname: messagebroker
      Retry__ConnectDelay: 10
      Retry__MaxAttempts: 50
      Retry__RetryDelay: 10
    image: loginvsi2/applicationcollections:1.1.2
    networks:
    - front
    - messaging
    restart: always
  applicationruns:
    depends_on:
    - identityserver
    - messagebroker
    deploy:
      restart_policy:
        condition: any
    environment:
      CORS__AlternativeHostUrl: https://localhost.loginvsi.com:4200
      DB__ConnectionString: ${CONNECTION_STRING};Database=ApplicationRuns;
      DB__DbType: ${DB_TYPE}
      Hosting__VirtualDirectory: applicationRuns
      IdentityProvider__Authority: http://identityserver/identityserver
      MessageBroker__Hostname: messagebroker
      Retry__ConnectDelay: 10
      Retry__MaxAttempts: 50
      Retry__RetryDelay: 10
    image: loginvsi2/applicationruns:1.1.0
    networks:
    - front
    - messaging
    restart: always
  applications:
    depends_on:
    - identityserver
    - messagebroker
    deploy:
      restart_policy:
        condition: any
    environment:
      CORS__AlternativeHostUrl: https://localhost.loginvsi.com:4200
      DB__ConnectionString: ${CONNECTION_STRING};Database=Applications;
      DB__DbType: ${DB_TYPE}
      Hosting__VirtualDirectory: applications
      IdentityProvider__Authority: http://identityserver/identityserver
      MessageBroker__Hostname: messagebroker
      Retry__ConnectDelay: 10
      Retry__MaxAttempts: 50
      Retry__RetryDelay: 10
    image: loginvsi2/applications:1.1.0
    networks:
    - front
    - messaging
    restart: always
  comparisonengine:
    depends_on:
    - messagebroker
    - identityserver
    deploy:
      restart_policy:
        condition: any
    environment:
      ComparisonEngine__MatchPercentageThreshold: 95
      ComparisonEngine__OperationMode: 1
      IdentityProvider__Authority: http://identityserver/identityserver
      MessageBroker__Hostname: messagebroker
      Services__ApplicationCollectionsUrl: http://applicationcollections/ApplicationCollections
      Services__ApplicationRunsUrl: http://applicationruns/ApplicationRuns
      Services__ApplicationsUrl: http://applications/Applications
      Services__HubUrl: ws://notificationshub/notificationsHub
      Services__ImageStorageUrl: http://imagestorage/ImageStorage
      Services__LicensingUrl: http://licensing/Licensing
      Services__RunAssignmentsUrl: http://runassignments/RunAssignments
      Services__RunHistoryUrl: http://runhistory/RunHistory
    image: loginvsi2/comparisonengine:1.1.2
    networks:
    - front
    - messaging
    restart: always
  contentdelivery:
    depends_on:
    - identityserver
    - messagebroker
    deploy:
      restart_policy:
        condition: any
    environment:
      Hosting__HostUrls: ${ALLOWED_CLIENT_URLS}
      Hosting__VirtualDirectory: contentDelivery
      IdentityProvider__Authority: http://identityserver/identityserver
      MessageBroker__Hostname: messagebroker
      Retry__ConnectDelay: 10
      Retry__MaxAttempts: 50
      Retry__RetryDelay: 10
      Version__Number: '1.1.30'
    image: loginvsi2/contentdelivery:1.1.1
    networks:
    - front
    - messaging
    restart: always
    secrets:
    - ENGINE_SECRET
  gateway:
    deploy:
      restart_policy:
        condition: any
    environment:
      START_DELAY: 20
    image: loginvsi2/gateway:1.1.0
    networks:
    - front
    - messaging
    ports:
    - ${GATEWAY_PORT}:443
    - 80:80
    restart: always
    secrets:
    - VSI_SSL_CERTIFICATE
    - VSI_SSL_CERTIFICATE_KEY
    - VSI_SSL_CERTIFICATE_KEY_PASSWORD
  identityserver:
    depends_on:
    - identityserverDb
    deploy:
      restart_policy:
        condition: any
    environment:
      Appliance_Version: 'a040'
      DB__ConnectionString: Server=identityserverDb;Database=IdentityServer;Username=postgres;
      DB__DbType: PostgreSQL
      Hosting__HostUrls: ${ALLOWED_CLIENT_URLS}
      Hosting__VirtualDirectory: identityserver
      Version__Number: '1.1.30'
    image: loginvsi2/identityserver:0.1.5
    networks:
    - front
    - databases
    restart: always
    secrets:
    - ADMIN_PASSWORD
    - USER_PASSWORD
    - ENGINE_SECRET
  identityserverDb:
    deploy:
      restart_policy:
        condition: any
    image: postgres:9
    networks:
    - databases
    restart: always
    volumes:
    - ${DB_ROOT}/identityserverDb:/var/lib/postgresql/data
  imagestorage:
    depends_on:
    - identityserver
    - messagebroker
    deploy:
      restart_policy:
        condition: any
    environment:
      CORS__AlternativeHostUrl: https://localhost.loginvsi.com:4200
      DB__ConnectionString: ${CONNECTION_STRING};Database=ImageStorage;
      DB__DbType: ${DB_TYPE}
      Hosting__VirtualDirectory: imageStorage
      IdentityProvider__Authority: http://identityserver/identityserver
      MessageBroker__Hostname: messagebroker
      Retry__ConnectDelay: 10
      Retry__MaxAttempts: 50
      Retry__RetryDelay: 10
    image: loginvsi2/imagestorage:1.1.0
    networks:
    - front
    - messaging
    restart: always
  licensing:
    depends_on:
    - identityserver
    - messagebroker
    deploy:
      restart_policy:
        condition: any
    environment:
      CORS__AlternativeHostUrl: https://localhost.loginvsi.com:4200
      DB__ConnectionString: ${CONNECTION_STRING};Database=Licensing;
      DB__DbType: ${DB_TYPE}
      Hosting__VirtualDirectory: licensing
      IdentityProvider__Authority: http://identityserver/identityserver
      MessageBroker__Hostname: messagebroker
      Retry__ConnectDelay: 10
      Retry__MaxAttempts: 50
      Retry__RetryDelay: 10
    image: loginvsi2/licensing:1.1.0
    networks:
    - front
    - messaging
    restart: always
  messagebroker:
    deploy:
      restart_policy:
        condition: any
    hostname: rabbitMQ-${COMPOSE_PROJECT_NAME}
    image: rabbitmq:3.6.12-management
    networks:
    - messaging
    restart: always
    volumes:
    - ${DB_ROOT}/messagebroker:/var/lib/rabbitmq/mnesia
  notificationshub:
    deploy:
      restart_policy:
        condition: any
    environment:
      Hosting__VirtualDirectory: notificationsHub
      IdentityProvider__Authority: http://identityserver/identityServer
    image: loginvsi2/notificationshub:1.1.0
    networks:
    - front
    restart: always
  notificationsworker:
    depends_on:
    - messagebroker
    - identityserver
    deploy:
      restart_policy:
        condition: any
    environment:
      ComparisonEngine__MatchPercentageThreshold: 95
      ComparisonEngine__OperationMode: 1
      IdentityProvider__Authority: http://identityserver/identityserver
      MessageBroker__Hostname: messagebroker
      Services__ApplicationCollectionsUrl: http://applicationcollections/ApplicationCollections
      Services__ApplicationRunsUrl: http://applicationruns/ApplicationRuns
      Services__ApplicationsUrl: http://applications/Applications
      Services__HubUrl: ws://notificationshub/notificationsHub
      Services__ImageStorageUrl: http://imagestorage/ImageStorage
      Services__LicensingUrl: http://licensing/Licensing
      Services__RunAssignmentsUrl: http://runassignments/RunAssignments
      Services__RunHistoryUrl: http://runhistory/RunHistory
    image: loginvsi2/notificationsworker:1.1.0
    networks:
    - front
    - messaging
    restart: always
  propagationengine:
    depends_on:
    - messagebroker
    - identityserver
    deploy:
      restart_policy:
        condition: any
    environment:
      ComparisonEngine__MatchPercentageThreshold: 95
      ComparisonEngine__OperationMode: 2
      Hosting__VirtualDirectory: propagationEngine
      IdentityProvider__Authority: http://identityserver/identityserver
      MessageBroker__Hostname: messagebroker
      Services__ApplicationRunsUrl: http://applicationruns
      Services__HubUrl: ws://notificationshub/notificationsHub
      Services__ImageStorageUrl: http://imagestorage
      Services__LicensingUrl: http://licensing
    image: loginvsi2/comparisonengine:1.1.2
    networks:
    - front
    - messaging
    restart: always
  runassignments:
    depends_on:
    - identityserver
    - messagebroker
    deploy:
      restart_policy:
        condition: any
    environment:
      CORS__AlternativeHostUrl: https://localhost.loginvsi.com:4200
      DB__ConnectionString: ${CONNECTION_STRING};Database=RunAssignments;
      DB__DbType: ${DB_TYPE}
      Hosting__VirtualDirectory: runAssignments
      IdentityProvider__Authority: http://identityserver/identityserver
      MessageBroker__Hostname: messagebroker
      Retry__ConnectDelay: 10
      Retry__MaxAttempts: 50
      Retry__RetryDelay: 10
    image: loginvsi2/runassignments:1.1.0
    networks:
    - front
    - messaging
    restart: always
  runhistory:
    depends_on:
    - identityserver
    - messagebroker
    deploy:
      restart_policy:
        condition: any
    environment:
      CORS__AlternativeHostUrl: https://localhost.loginvsi.com:4200
      DB__ConnectionString: ${CONNECTION_STRING};Database=RunHistory;
      DB__DbType: ${DB_TYPE}
      Hosting__VirtualDirectory: runHistory
      IdentityProvider__Authority: http://identityserver/identityserver
      MessageBroker__Hostname: messagebroker
      Retry__ConnectDelay: 10
      Retry__MaxAttempts: 50
      Retry__RetryDelay: 10
    image: loginvsi2/runhistory:1.1.0
    networks:
    - front
    - messaging
    restart: always
  serverurls:
    deploy:
      restart_policy:
        condition: any
    environment:
      Hosting__VirtualDirectory: serverUrls
    image: loginvsi2/serverurls:1.1.0
    networks:
    - front
    restart: always
  synchronizationworker:
    depends_on:
    - messagebroker
    - identityserver
    deploy:
      restart_policy:
        condition: any
    environment:
      ComparisonEngine__MatchPercentageThreshold: 95
      ComparisonEngine__OperationMode: 1
      IdentityProvider__Authority: http://identityserver/identityserver
      MessageBroker__Hostname: messagebroker
      Services__ApplicationCollectionsUrl: http://applicationcollections/ApplicationCollections
      Services__ApplicationRunsUrl: http://applicationruns/ApplicationRuns
      Services__ApplicationsUrl: http://applications/Applications
      Services__HubUrl: ws://notificationshub/notificationsHub
      Services__ImageStorageUrl: http://imagestorage/ImageStorage
      Services__LicensingUrl: http://licensing/Licensing
      Services__RunAssignmentsUrl: http://runassignments/RunAssignments
      Services__RunHistoryUrl: http://runhistory/RunHistory
    image: loginvsi2/synchronizationworker:1.1.0
    networks:
    - front
    - messaging
    restart: always
  ui:
    deploy:
      restart_policy:
        condition: any
    image: loginvsi2/userinterface:1.1.0
    networks:
    - front
    restart: always
version: "3.4"

