networks:
  databases:
    driver: overlay
  front:
    driver: overlay
  messaging:
    driver: overlay
secrets:
  ADMIN_PASSWORD:
    external: true
  USER_PASSWORD:
    external: true
  VSI_SSL_CERTIFICATE:
    file: ${SSL_CERTIFICATE_PATH}
  VSI_SSL_CERTIFICATE_KEY:
    file: ${SSL_CERTIFICATE_KEY_PATH}
  VSI_SSL_CERTIFICATE_KEY_PASSWORD:
    external: true
services:
  applicationCollectionsDb:
    deploy:
      restart_policy:
        condition: on-failure
    image: postgres:9
    networks:
    - databases
    restart: always
  applicationRunsDb:
    deploy:
      restart_policy:
        condition: on-failure
    image: postgres:9
    networks:
    - databases
    restart: always
  applicationcollections:
    depends_on:
    - applicationCollectionsDb
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      DB__ConnectionString: Server=applicationCollectionsDb;Database=ApplicationCollections;Username=postgres;
      DB__DbType: PostgreSQL
      Hosting__VirtualDirectory: applicationCollections
      IdentityProvider__Authority: http://identityserver/identityServer
      MessageBroker__Hostname: messagebroker
      Version__Number: '0.9.24'
    image: loginvsi2/applicationcollections:0.5.0
    networks:
    - databases
    - front
    - messaging
    restart: always
  applicationruns:
    depends_on:
    - applicationRunsDb
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      DB__ConnectionString: Server=applicationRunsDb;Database=ApplicationRuns;Username=postgres;
      DB__DbType: PostgreSQL
      Hosting__VirtualDirectory: applicationRuns
      IdentityProvider__Authority: http://identityserver/identityServer
      MessageBroker__Hostname: messagebroker
      Version__Number: '0.9.24'
    image: loginvsi2/applicationruns:0.5.0
    networks:
    - databases
    - front
    - messaging
    restart: always
  applications:
    depends_on:
    - applicationsDb
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      DB__ConnectionString: Server=applicationsDb;Database=Applications;Username=postgres;
      DB__DbType: PostgreSQL
      Hosting__VirtualDirectory: applications
      IdentityProvider__Authority: http://identityserver/identityServer
      MessageBroker__Hostname: messagebroker
      Version__Number: '0.9.24'
    image: loginvsi2/applications:0.5.0
    networks:
    - databases
    - front
    - messaging
    restart: always
  applicationsDb:
    deploy:
      restart_policy:
        condition: on-failure
    image: postgres:9
    networks:
    - databases
    restart: always
  comparisonengine:
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      ComparisonEngine__MatchPercentageThreshold: 95
      IdentityProvider__Authority: http://identityserver/identityServer
      MessageBroker__Hostname: messagebroker
      Services__ApplicationRunsUrl: http://applicationruns
      Services__ImageStorageUrl: http://imagestorage
    image: loginvsi2/comparisonengine:0.5.0
    networks:
    - front
    - messaging
    restart: always
  contentdelivery:
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      Hosting__HostUrls: ${ALLOWED_CLIENT_URLS}
    image: loginvsi2/contentdelivery:0.5.6
    networks:
    - front
    restart: always
  gateway:
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      START_DELAY: 10
    image: loginvsi2/gateway:0.2.0
    networks:
    - front
    - messaging
    ports:
    - ${GATEWAY_PORT}:443
    - 80:80
    restart: always
    secrets:
    - VSI_SSL_CERTIFICATE
    - VSI_SSL_CERTIFICATE_KEY
    - VSI_SSL_CERTIFICATE_KEY_PASSWORD
  identityserver:
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      Hosting__HostUrls: ${ALLOWED_CLIENT_URLS}
      Hosting__VirtualDirectory: identityServer
      Version__Number: '0.9.24'
    image: loginvsi2/identityserver:0.1.2
    networks:
    - front
    restart: always
    secrets:
    - ADMIN_PASSWORD
    - USER_PASSWORD
  imageStorageDb:
    deploy:
      restart_policy:
        condition: on-failure
    image: postgres:9
    networks:
    - databases
    restart: always
  imagestorage:
    depends_on:
    - imageStorageDb
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      DB__ConnectionString: Server=imageStorageDb;Database=ImageStorage;Username=postgres;
      DB__DbType: PostgreSQL
      Hosting__VirtualDirectory: imageStorage
      IdentityProvider__Authority: http://identityserver/identityServer
      Version__Number: '0.9.24'
    image: loginvsi2/imagestorage:0.2.5
    networks:
    - databases
    - front
    - messaging
    restart: always
  messagebroker:
    deploy:
      restart_policy:
        condition: on-failure
    hostname: rabbitMQ-${COMPOSE_PROJECT_NAME}
    image: rabbitmq:3.7.4-management
    networks:
    - messaging
    restart: always
  notificationshub:
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      Hosting__VirtualDirectory: notificationsHub
      IdentityProvider__Authority: http://identityserver/identityServer
    image: loginvsi2/notificationshub:0.2.0
    networks:
    - front
    restart: always
  notificationsworker:
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      IdentityProvider__Authority: http://identityserver/identityServer
      MessageBroker__Hostname: messagebroker
      Services__HubUrl: ws://notificationshub/notificationsHub
    image: loginvsi2/notificationsworker:0.2.0
    networks:
    - front
    - messaging
    restart: always
  runAssignmentsDb:
    deploy:
      restart_policy:
        condition: on-failure
    image: postgres:9
    networks:
    - databases
    restart: always
  runHistoryDb:
    deploy:
      restart_policy:
        condition: on-failure
    image: postgres:9
    networks:
    - databases
    restart: always
  runassignments:
    depends_on:
    - runAssignmentsDb
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      DB__ConnectionString: Server=runAssignmentsDb;Database=RunAssignments;Username=postgres;
      DB__DbType: PostgreSQL
      Hosting__VirtualDirectory: runAssignments
      IdentityProvider__Authority: http://identityserver/identityServer
      MessageBroker__Hostname: messagebroker
      Version__Number: '0.9.24'
    image: loginvsi2/runassignments:0.1.2
    networks:
    - databases
    - front
    - messaging
    restart: always
  runhistory:
    depends_on:
    - runHistoryDb
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      DB__ConnectionString: Server=runHistoryDb;Database=RunHistory;Username=postgres;
      DB__DbType: PostgreSQL
      Hosting__VirtualDirectory: runHistory
      IdentityProvider__Authority: http://identityserver/identityServer
      MessageBroker__Hostname: messagebroker
      Version__Number: '0.9.24'
    image: loginvsi2/runhistory:0.5.0
    networks:
    - databases
    - front
    - messaging
    restart: always
  serverurls:
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      Hosting__VirtualDirectory: serverUrls
    image: loginvsi2/serverurls:0.2.0
    networks:
    - front
    restart: always
  synchronizationworker:
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      IdentityProvider__Authority: http://identityserver/identityServer
      MessageBroker__Hostname: messagebroker
      Services__ApplicationCollectionsUrl: http://applicationcollections
      Services__ApplicationRunsUrl: http://applicationruns
      Services__ApplicationsUrl: http://applications
      Services__RunAssignmentsUrl: http://runassignments
      Services__RunHistoryUrl: http://runhistory
    image: loginvsi2/synchronizationworker:0.3.0
    networks:
    - front
    - messaging
    restart: always
  ui:
    deploy:
      restart_policy:
        condition: on-failure
    image: loginvsi2/userinterface:0.5.5
    networks:
    - front
    restart: always
version: "3.1"

