networks:
  front:
    driver: bridge
  messaging:
    driver: bridge
secrets:
  ADMIN_PASSWORD:
    file: ${SSL_CERTIFICATE_KEY_PASSWORD_PATH}
  USER_PASSWORD:
    file: ${SSL_CERTIFICATE_KEY_PASSWORD_PATH}
  VSI_SSL_CERTIFICATE:
    file: ${SSL_CERTIFICATE_PATH}
  VSI_SSL_CERTIFICATE_KEY:
    file: ${SSL_CERTIFICATE_KEY_PATH}
  VSI_SSL_CERTIFICATE_KEY_PASSWORD:
    file: ${SSL_CERTIFICATE_KEY_PASSWORD_PATH}
services:
  applicationcollections:
    depends_on:
    - identityserver
    - messagebroker
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      DB__ConnectionString: ${CONNECTION_STRING}
      DB__DbType: ${DB_TYPE}
      Hosting__VirtualDirectory: applicationcollections
      IdentityProvider__Authority: http://identityserver/identityServer
      MessageBroker__Hostname: messagebroker
      Version__Number: '99.1.33'
    image: loginvsi2/applicationcollections:dev
    networks:
    - front
    - messaging
    restart: always
  applicationruns:
    depends_on:
    - identityserver
    - messagebroker
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      DB__ConnectionString: ${CONNECTION_STRING}
      DB__DbType: ${DB_TYPE}
      Hosting__VirtualDirectory: applicationruns
      IdentityProvider__Authority: http://identityserver/identityServer
      MessageBroker__Hostname: messagebroker
      Version__Number: '99.1.33'
    image: loginvsi2/applicationruns:dev
    networks:
    - front
    - messaging
    restart: always
  applications:
    depends_on:
    - identityserver
    - messagebroker
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      DB__ConnectionString: ${CONNECTION_STRING}
      DB__DbType: ${DB_TYPE}
      Hosting__VirtualDirectory: applications
      IdentityProvider__Authority: http://identityserver/identityServer
      MessageBroker__Hostname: messagebroker
      Version__Number: '99.1.33'
    image: loginvsi2/applications:dev
    networks:
    - front
    - messaging
    restart: always
  comparisonengine:
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      IdentityProvider__Authority: http://identityserver/identityServer
      MessageBroker__Hostname: messagebroker
      Services__ApplicationRunsUrl: http://applicationruns
    image: loginvsi2/comparisonengine:dev
    networks:
    - front
    - messaging
    restart: always
  contentdelivery:
    deploy:
      restart_policy:
        condition: on-failure
    image: loginvsi2/contentdelivery:dev
    networks:
    - front
    restart: always
  gateway:
    depends_on:
    - applications
    deploy:
      restart_policy:
        condition: on-failure
    image: loginvsi2/gateway:dev
    networks:
    - front
    - messaging
    ports:
    - ${GATEWAY_PORT}:443
    restart: always
    secrets:
    - VSI_SSL_CERTIFICATE
    - VSI_SSL_CERTIFICATE_KEY
    - VSI_SSL_CERTIFICATE_KEY_PASSWORD
  identityserver:
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      Hosting__HostUrls: ${ALLOWED_CLIENT_URLS}
      Hosting__VirtualDirectory: identityserver
      Version__Number: '99.1.33'
    image: loginvsi2/identityserver:dev
    networks:
    - front
    restart: always
    secrets:
    - ADMIN_PASSWORD
    - USER_PASSWORD
  imagestorage:
    depends_on:
    - identityserver
    - messagebroker
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      CORS__AlternativeHostUrl: https://localhost.loginvsi.com:4200
      DB__ConnectionString: ${CONNECTION_STRING}
      DB__DbType: ${DB_TYPE}
      Hosting__VirtualDirectory: imagestorage
      IdentityProvider__Authority: http://identityserver/identityServer
      Version__Number: '99.1.33'
    image: loginvsi2/imagestorage:dev
    networks:
    - front
    - messaging
    restart: always
  messagebroker:
    deploy:
      restart_policy:
        condition: on-failure
    hostname: rabbitMQ-${COMPOSE_PROJECT_NAME}
    image: rabbitmq:3.7.4-management
    networks:
    - messaging
    restart: always
  notificationshub:
    depends_on:
    - identityserver
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      Hosting__VirtualDirectory: notificationshub
      IdentityProvider__Authority: http://identityserver/identityServer
    image: loginvsi2/notificationshub:dev
    networks:
    - front
    restart: always
  notificationsworker:
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      IdentityProvider__Authority: http://identityserver/identityServer
      MessageBroker__Hostname: messagebroker
      Services__HubUrl: ws://notificationshub/notificationsHub
    image: loginvsi2/notificationsworker:dev
    networks:
    - front
    - messaging
    restart: always
  portainer:
    command: -d /data -H unix:///var/run/docker.sock --admin-password '$$2y$$05$$DTUYaqFuY0ot0BuUqKE4d.KyQmBzZiUe64rl6QLTYhS/9Nl000vK.'
    deploy:
      restart_policy:
        condition: on-failure
    image: portainer/portainer
    ports:
    - 9000:9000
    restart: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  runhistory:
    depends_on:
    - identityserver
    - messagebroker
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      DB__ConnectionString: ${CONNECTION_STRING}
      DB__DbType: ${DB_TYPE}
      Hosting__VirtualDirectory: runhistory
      IdentityProvider__Authority: http://identityserver/identityServer
      MessageBroker__Hostname: messagebroker
      Version__Number: '99.1.33'
    image: loginvsi2/runhistory:dev
    networks:
    - front
    - messaging
    restart: always
  serverurls:
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      Hosting__VirtualDirectory: serverurls
    image: loginvsi2/serverurls:dev
    networks:
    - front
    restart: always
  synchronizationworker:
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      IdentityProvider__Authority: http://identityserver/identityServer
      MessageBroker__Hostname: messagebroker
      Services__ApplicationCollectionsUrl: http://applicationcollections
      Services__ApplicationRunsUrl: http://applicationruns
      Services__ApplicationsUrl: http://applications
      Services__ReferenceImagesUrl: http://referenceimages
      Services__RunHistoryUrl: http://runhistory
    image: loginvsi2/synchronizationworker:dev
    networks:
    - front
    - messaging
    restart: always
  ui:
    deploy:
      restart_policy:
        condition: on-failure
    image: loginvsi2/userinterface:dev
    networks:
    - front
    restart: always
version: "3.1"

